apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-pvc
  namespace: halo-system
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: halo-pv
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
