apiVersion: apps/v1
kind: Deployment
metadata:
  name: halo-server
  namespace: halo-system
  labels:
    app: halo-server
spec:
  selector:
    matchLabels:
      app: halo-server
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: halo-server
    spec:
      volumes:
        - name: halo-storage
          persistentVolumeClaim:
            claimName: halo-pvc
      containers:
        - name: halo
          image: "ghcr.io/halo-dev/halodev:next"
          imagePullPolicy: IfNotPresent
          ports:
            - name: halo-port
              containerPort: 8090
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          volumeMounts:
            - name: halo-storage
              mountPath: /root/halo-next
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: halo-port
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: halo-port
          startupProbe:
            httpGet:
              path: /actuator/health
              port: halo-port
