apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halo-admin-ingress
  namespace: halo-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "next.ryanc.cc"
      http:
        paths:
          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: halo-admin-service
                port:
                  number: 8090
