apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-pvc
  namespace: halo-system
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
